include::header.adoc[]

:title: Assignment 09: Follow the thread
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1
:stem: latexmath
:ASST: A09

= {title}

*Due Friday, November 8 before midnight*

The goals for this assignment are:

* Implement multi-thread algorithms using the pthread library

[discrete]
== Update your repository

Do a *fetch upstream* to obtain the basecode for this assignment. 

Using the command line

* Open terminal and change your current directory to your assignment repository.
* Run the command `git fetch upstream`
* Run the command `git merge upstream/master`

Your repository should now contain a new folder named `{ASST}`.

The `fetch` and `merge` commands update your repository with any changes from the original.

:sectnums:

= Grep

In the file, `grep.c`, implement a program that uses N threads to search for a keyword 
recursively in a set of files or directories. This question implements a simplified version of 
the command `grep`.

[source, subs="quotes"]
----
$ **make grep**
gcc -g -Wall -Wvla -Werror grep.c -o grep -lpthreads
$ **./grep Skeleton `find /home/alinen/public/dart/ -name "*.c"`
----

Requirements:


= Code Analysis

This question has two parts. In the first part, you will implement a tree data structure that can contain 
any number of children. In the second part, you will use this data structure to store and query 
the class hierarchy of a large open-source repository.

== Tree

Implement a tree data structure capable of storing any number of children. 

== Class hierarchy

Using N threads, construct the class hierarchy for the open-source repository, `dart`, stored on goldengate at `/home/alinen/public/dart`.

= Submit your work

Submit both your code and images.

1) Push your code work to github

[source]
----
$ git status
$ git add . 
$ git status
$ git commit -m "assignment complete"
$ git status
$ git push
$ git status
----


= Grading Rubric

*Assignment rubrics*

Grades are out of 4 points.

* (1 points) Grep
** (0.1 points) style and header comment
** (0.4 points) 
** (0.5 points) no memory errors
* (2 points) Tree
** (0.1 points) style and header comment
** (0.9 points) 
** (1 points) no memory errors
* (1 points) Class Hierarchy 
** (0.1 points) style and header comment
** (0.4 points) 
** (0.5 points) no memory errors

*Code rubrics*

For full credit, your C programs must be feature-complete, robust (e.g. run without memory errors or crashing) and 
have good style.

* Some credit lost for missing features or bugs, depending on severity of error
* -5% for style errors. See the link:../codingstandard.html[class coding style] here.
* -50% for memory errors
* -100% for failure to checkin work to Github
* -100% for failure to compile on linux using make

