include::header.adoc[]

:title: Assignment 09: Follow the thread
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1
:stem: latexmath
:ASST: A09

= {title}

*Due Friday, November 8 before midnight*

The goals for this assignment are:

* Implement multi-thread algorithms using the pthread library

[discrete]
== Update your repository

Do a *fetch upstream* to obtain the basecode for this assignment. 

Using the command line

* Open terminal and change your current directory to your assignment repository.
* Run the command `git fetch upstream`
* Run the command `git merge upstream/master`

Your repository should now contain a new folder named `{ASST}`.

The `fetch` and `merge` commands update your repository with any changes from the original.

:sectnums:


= Search

In the file, `search.c`, implement a program that uses N threads to search for a value in a list. 
Your program should load the binary file `data.bin` and then split the workload between the N threads.

[source, subs="quotes"]
----
$ **make search**
gcc -g -Wall -Wvla -Werror search.c -o search -lpthreads
$ **./search 2**
Enter a value to search: **3**
Thread 2 found 3 at index 5003
$ **./search 2**
Enter a value to search: **5003**
Thread 1 found 5003 at index 3
$ **./search 2**
Enter a value to search: **-2**
Not found!
----

Requirements:

* Your program should load the _binary_ file, `data.bin`. This file stores a sequence of non-sorted integers. The first value in the file holds the number of integers. link:https://github.com/BrynMawr-CS223-S22/class-examples/blob/main/lec10/readbinary.c[This class example shows how to read in binary data]. Your program should read the first integer to get the size, malloc an array with the given size, and then read in the data as a big block.
* Your program should split the work of searching through the data between each thread.

= Matrix multiplication

= Grep

= Submit your work

Submit both your code and images.

1) Push your code work to github

[source]
----
$ git status
$ git add . 
$ git status
$ git commit -m "assignment complete"
$ git status
$ git push
$ git status
----


= Grading Rubric

*Assignment rubrics*

Grades are out of 4 points.

* (1 points) Simple Search
** (0.1 points) style and header comment
** (0.4 points) 
** (0.5 points) no memory errors
* (1 points) Matrix Multiply
** (0.1 points) style and header comment
** (1.4 points) 
** (1.5 points) no memory errors
* (2 points) Grep
** (0.1 points) style and header comment
** (0.9 points) 
** (1 points) no memory errors

*Code rubrics*

For full credit, your C programs must be feature-complete, robust (e.g. run without memory errors or crashing) and 
have good style.

* Some credit lost for missing features or bugs, depending on severity of error
* -5% for style errors. See the link:../codingstandard.html[class coding style] here.
* -50% for memory errors
* -100% for failure to checkin work to Github
* -100% for failure to compile on linux using make

