== Academic Integrity

At Bryn Mawr, we assume students are trustworthy and work with honesty and
integrity.
link:https://www.brynmawr.edu/deans/academic-and-community-integrity[Look here
for information about Bryn Mawr's Honor Code.]. Obviously, quizzes and exams must 
be your own work. However, you will be allowed to work with others on assignments; 
although *everyone must still submit their own work.* 

Programming is a creative skill that takes practice and effort to develop.  It's
_essential_ that you develop your own skills for developing algorithms and
implementing them through programs. 

Quizzes and exams will be _closed book_. You will be able to bring a 
single cheat sheet with you. 

The goal of assignments and labs is to help you prepare for quizzes and exams.
The goals of quizzes and exams are to help you internalize the material (and
provide feedback on how well you understand the material) so that you can grow
towards your full potential as someone who can solve technical problems and who
can create their own systems and devices.  If you can sit down, focus, and
answer questions within a time limit, you understand the material and can
communicate that understanding to someone else. 
*If you are doing worksheets and assignments but not doing well on quizzes, 
you need to re-think how you are approaching assignments.* You can assess
whether you're  effectively using assignments to learn if you can do the
following after completing it:

* Explain how your code works to someone else, without looking at your code
* Explain the system calls necessary to complete your assignment without looking them up online
* Write a similar program within a few minutes, without looking up help online

Here is advice that has worked well for me. 

* Most beneficial: writing my own programs from scratch, followed by stepping line by line using a debugger to make sure it worked as intended
* When stuck, debugging the program with the help of a more experienced developer
* Comparing my solutions with others _after I finished my own solution_

I do not recommend relying on stack overflow, copying old solutions, and using Chat-GPT. 
*The absolute worst way to program is by cutting and pasting code you don't understand, guessing your 
way to something that kind of works.* 

I am not going to police how you study and develop skills.  If you're not doing
well, you need to figure out how to work differently. 

Do's: 

* DO discuss ideas and approaches with your classmates.
* DO discuss ideas and approaches with your TAs and instructor.
* DO search for documentation and sample programs for built-in C functions and C syntax.
* DO use code from our text books and class (with attribution).

Don'ts:

* DON'T use Chat-GPT (or other LLMs) to generate solutions.
* DON'T copy full solutions, from online tutorials, previous students, etc
* DON'T use functions and C syntax that is disallowed by the Makefile. We are deliberately using simple and portable C.
* DON'T modify any basecode that comes with your assignment. 
* DON'T ever share your code with other students.

It's ultimately up to you to learn from your assignments! No one is
going to hire you to do work that they can easily do themselves using a search
or AI program generator. You can only build expertise with experience and practice.

One final point: we will be using open-source repositories for homeworks in this
class.  Thus, it will be possible to see what other students (and previous
students) have submitted.  If you copy from others' repositories, it will be
obvious, including potential employers! Only look at other solutions after you
have finished your own first!
